### ISSUE TITLE
Swords unable to be removed nor are the holders able to be broken on 1.16.2

### ISSUE THREAD

**Issue by Danhack1** [sokratis12GR/Sword-Displays#14]
Firstly, thanks for your work :) 

Second! The mod works great when I first use a sword holder, but then once I close Minecraft and re-open it, the sword is stuck and cannot be removed, nor can I break the sword holder. I am on MC 1.16.4 and am running it on the Client side. 

I am shift clicking and right clicking and doing everything right, but they seem to be stuck! 

Thanks again

**Comment by sokratis12GR** [comment]
Hello, thanks for the issue report!

Are you shift right clicking with an empty hand? Because you hand must be empty in order to get the sword.

**Comment by Danhack1** [comment]
Hi!

Yes, empty hand and shift-right clicking, the sword also doesn't rotate,
just completely frozen!

**Comment by sokratis12GR** [comment]
Alright, will have a throughout investigation later, thanks again.

**Comment by sokratis12GR** [comment]
Ughm one last thing, we the blocks placed before the update?
Which version of sword displays are you using?

Depending how you answer them, you might need to go into creative mode to break them and replace them.

**Comment by Danhack1** [comment]
I'm using 1.16.1.1.1 (the newest version) and have only used that version!

**Comment by sokratis12GR** [comment]
I'm sorry but I'm unable to reproduce the issue.
Would it be possible to provide me with details how the issue occured?

**Comment by Danhack1** [comment]
Sure, I'm taking a video that will show how the mod works when I first use a sword display then when I log out and back in the sword display stops working.

**Comment by Danhack1** [comment]
[Sworddisplaymod - SD 480p.mov.zip](https://github.com/sokratis12GR/Sword-Displays/files/5707099/Sworddisplaymod.-.SD.480p.mov.zip)

**Comment by sokratis12GR** [comment]
Alright thanks for reporting this, there will be a release containing the fix in a bit.
Sword Displays [1.16.2-1.1.2](https://www.curseforge.com/minecraft/mc-mods/sword-displays/files/3141144)
