### ISSUE TITLE
Can't display Tinker's Construct broadswords

### ISSUE THREAD

**Issue by Random832** [sokratis12GR/Sword-Displays#17]
There is a whitelist for item IDs that includes `tconstruct:broadsword`, but it looks like in 1.16 it was `tconstruct:broad_sword`, and in 1.18 it is just `tconstruct:sword`.

Also it may be worth considering adding an item tag for swords, so that mods and users can configure this with datapacks, though the tag system in Forge for 1.18.2 is currently a work in progress.

**Comment by sokratis12GR** [comment]
Thanks for the report, will look into it first thing tomorrow morning.

**Comment by sokratis12GR** [comment]
Released a new update.
Version [Sword Displays 1.18.1-1.1.0](https://www.curseforge.com/minecraft/mc-mods/sword-displays/files/3676269) should now correctly support both 1.18.1 and 1.18.2, replaced the special items "whitelist" with the new tag list functionality that can be found inside `sworddisplay:swords` or well `data/sworddisplay/tags/items/swords.json`

Thanks for your suggestion ^^.
