### ISSUE TITLE
1.18.2 Crash

### ISSUE THREAD

**Issue by FoxfireDragon** [sokratis12GR/Sword-Displays#18]
[latest.log](https://github.com/sokratis12GR/Sword-Displays/files/8430240/latest.log)
crash log, removing sword displays fixed the issue

**Comment by sokratis12GR** [comment]
Thanks for the issue report, [Sword Displays 1.18.2-1.0.0](https://www.curseforge.com/minecraft/mc-mods/sword-displays/files/3737552) should fix this issue.
