### ISSUE TITLE
1.15.2 - 1.2.0 - recipes broken - still

### ISSUE THREAD

**Issue by ArMoReDfUrY** [sokratis12GR/Sword-Displays#3]
wood recipes are good iron display is good.

both prismarine and the iron case recipes have the wrong result, they all make the iron display stand.

**Comment by sokratis12GR** [comment]
Ah somehow this slipped through, thanks for reporting it! Will release 1.15.2-1.2.1 shortly

**Comment by sokratis12GR** [comment]
[Sword Displays 1.15.2-1.2.1 should fix this](https://www.curseforge.com/minecraft/mc-mods/sword-displays/files/2996260)

**Comment by ArMoReDfUrY** [comment]
No worries 👍

**Comment by ArMoReDfUrY** [comment]
you missed one.

iron case recipe has wrong result.

**Comment by sokratis12GR** [comment]
Oh well, will include it in tomorrow's feature update..

**Comment by ArMoReDfUrY** [comment]
no worries, more for others. i know how to fix this stuff.

**Comment by sokratis12GR** [comment]
[Sword Displays 1.15.2-1.3.0 should fix this](https://www.curseforge.com/minecraft/mc-mods/sword-displays)

**Comment by ArMoReDfUrY** [comment]
just checked it out, looks great 👍
