### ISSUE TITLE
TLauncher Mac - Forge problem 1.15.2

### ISSUE THREAD

**Issue by Nonaoco** [sokratis12GR/Sword-Displays#6]
Image preview here: https://ibb.co/H2VPwbG

Please help me!! i download forge from and placed in /mods/ folder but not work!!!
http://files.minecraftforge.net/

**Comment by AzureDoom** [comment]
You have an old version, update your forge. It says right there. Requires 31.2.22 and you have 31.1.61. Update yo forge.

**Comment by sokratis12GR** [comment]
Hello there,
This is a place to report sword displays bugs, not how to play modded Minecraft, but nevertheless.
You download the 1.15.2 version of forge from files.minecraftforge.net (in order for this mod to work) then you run the installer (the file that you just downloaded) the default settings should be ideal click next and install, after that you download the mod from the curseforge page, place it inside /mods/ and finally run Minecraft forge 1.15.2 and you should be good to go.
