### ISSUE TITLE
I cannot withdraw items. I used Shift+right click and nothing happened

### ISSUE THREAD

**Issue by elliothawkz2** [sokratis12GR/Sword-Displays#7]

**Comment by sokratis12GR** [comment]
Hello, thanks for reporting an issue.
Are you 100% sure you shift-rightclicked (the sneak button + right click) with an empty hand (without holding anything on your hand) ?

**Comment by elliothawkz2** [comment]
I did, and nothing happened, the only way I could withdraw the item was by destroying the display

**Comment by sokratis12GR** [comment]
Weird, please let me know the following:
Sword Displays version:
Server or Client:

**Comment by elliothawkz2** [comment]
Client

**Comment by elliothawkz2** [comment]
Nevermind I just got it fixed. Thanks for your help
