### ISSUE TITLE
Swords display sideways/ laying down. In sworddisplay-1.16.2-1.0.1

### ISSUE THREAD

**Issue by Mohotzgui** [sokratis12GR/Sword-Displays#8]
Not sure why but all the swords accept for Netherite and some from another Modpack display laying down and not standing upright. This would be ok butit is displayed large and outside of the glass. Otherwise I love this pack! Can you make it display the other tools as well?

**Comment by sokratis12GR** [comment]
Hello, I don't quite understand your issue..
Do you mean that the netherite and vanilla swords work fine on the displays but some others by other mods do not?
If so, please let me know which modpack you are using or show me the modlist used by the modpack (please if possible highlight the ones that add swords)
And maybe soon I'll release an update fixing that and adding the ability to store any item inside.

**Comment by Mohotzgui** [comment]
Sorry I meant that the Netherite sword works but the other vanilla ones do not. The mods that have swords in them appear to work as well. GildedIngot-1.3.0-1.16.2 and TrinityWeapons-1.16.2-1.5.0. The vanilla swords appear sideways. It looks cool unless trying to use a glass cased sword display.

**Comment by Mohotzgui** [comment]
"adding the ability to store any item inside" super awesome. Especially for Museum builds,

**Comment by sokratis12GR** [comment]
Oh, this should no longer be the case with the later releases.
